In [5]:
import pandas as pd
df = pd.read_csv("./data/HR.csv")


In [6]:
df.head(10)

satisfaction_level  last_evaluation  number_project  average_monthly_hours  \
0                0.38             0.53               2                    157   
1                0.80             0.86               5                    262   
2                0.11             0.88               7                    272   
3                0.72             0.87               5                    223   
4                0.37             0.52               2                    159   
5                0.41             0.50               2                    153   
6                0.10             0.77               6                    247   
7                0.92             0.85               5                    259   
8                0.89             1.00               5                    224   
9                0.42             0.53               2                    142   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   
5                   3              0     1                      0      sales   
6                   4              0     1                      0      sales   
7                   5              0     1                      0      sales   
8                   5              0     1                      0      sales   
9                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low  
5     low  
6     low  
7     low  
8     low  
9     low

In [7]:
df.mean()  # 均值

satisfaction_level         0.612839
last_evaluation           67.373732
number_project             3.802693
average_monthly_hours    201.041728
time_spend_company         3.498067
Work_accident              0.144581
left                       0.238235
promotion_last_5years      0.021264
dtype: float64

In [8]:
df.mode()  # 众数

satisfaction_level  last_evaluation  number_project  average_monthly_hours  \
0                 0.1             0.55             4.0                    135   
1                 NaN              NaN             NaN                    156   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                 3.0            0.0   0.0                    0.0      sales   
1                 NaN            NaN   NaN                    NaN        NaN   

  salary  
0    low  
1    NaN

In [9]:
df.median()  # 中位数

satisfaction_level         0.64
last_evaluation            0.72
number_project             4.00
average_monthly_hours    200.00
time_spend_company         3.00
Work_accident              0.00
left                       0.00
promotion_last_5years      0.00
dtype: float64

In [10]:
df.quantile(q=0.25)  # 分位数

satisfaction_level         0.44
last_evaluation            0.56
number_project             3.00
average_monthly_hours    156.00
time_spend_company         3.00
Work_accident              0.00
left                       0.00
promotion_last_5years      0.00
Name: 0.25, dtype: float64

In [11]:
df.std()  # 标准差

satisfaction_level          0.248623
last_evaluation          8164.407524
number_project              1.232733
average_monthly_hours      49.941815
time_spend_company          1.460053
Work_accident               0.351689
left                        0.426018
promotion_last_5years       0.144267
dtype: float64

In [12]:
df.var()  # 方差

satisfaction_level       6.181359e-02
last_evaluation          6.665755e+07
number_project           1.519630e+00
average_monthly_hours    2.494185e+03
time_spend_company       2.131754e+00
Work_accident            1.236854e-01
left                     1.814911e-01
promotion_last_5years    2.081307e-02
dtype: float64

In [13]:
df.sum() 

satisfaction_level                                                 9192.59
last_evaluation                                                1.01074e+06
number_project                                                       57048
average_monthly_hours                                              3016028
time_spend_company                                                   52478
Work_accident                                                         2169
left                                                                  3574
promotion_last_5years                                                  319
department               salessalessalessalessalessalessalessalessaless...
salary                   lowmediummediumlowlowlowlowlowlowlowlowlowlowl...
dtype: object

In [14]:
df.skew()  # 偏态系数

satisfaction_level        -0.476438
last_evaluation          122.482652
number_project             0.337774
average_monthly_hours      0.053225
time_spend_company         1.853530
Work_accident              2.021481
left                       1.229057
promotion_last_5years      6.637677
dtype: float64

In [15]:
df.kurt()  # 峰度系数

satisfaction_level          -0.670696
last_evaluation          15001.999987
number_project              -0.495810
average_monthly_hours       -1.135016
time_spend_company           4.774353
Work_accident                2.086664
left                        -0.489485
promotion_last_5years       42.064357
dtype: float64

In [16]:
import scipy.stats as ss
ss.norm.stats(moments="mvsk")

(array(0.), array(1.), array(0.), array(0.))

In [17]:
ss.norm.pdf(0.0)

0.3989422804014327

In [18]:
ss.norm.rvs(size=10)

array([ 0.34991793, -0.17120736,  1.47067709,  0.43448003,  1.0184275 ,
        2.07030893,  0.68812694,  1.15580832,  1.27185922,  0.7084775 ])

In [20]:
df.sample(n=10)  # 随机抽样

satisfaction_level  last_evaluation  number_project  \
2708                 0.49             0.77               4   
14147                0.53             0.80               2   
1273                 0.87             0.95               5   
1103                 0.38             0.52               2   
2254                 0.91             0.82               3   
4047                 0.67             0.81               3   
4359                 0.74             0.51               4   
10566                0.72             0.71               3   
4172                 0.94             0.84               3   
12492                0.11             0.83               6   

       average_monthly_hours  time_spend_company  Work_accident  left  \
2708                     218                   2              0     0   
14147                    225                   7              1     0   
1273                     227                   5              0     1   
1103                     156                   3              0     1   
2254                     183                   3              0     0   
4047                     221                   4              1     0   
4359                     246                   3              1     0   
10566                    133                   2              0     0   
4172                     210                   2              0     0   
12492                    244                   4              0     1   

       promotion_last_5years  department  salary  
2708                       0   technical     low  
14147                      1  management    high  
1273                       0     support  medium  
1103                       0   technical     low  
2254                       0   technical  medium  
4047                       0  accounting  medium  
4359                       0   marketing  medium  
10566                      0          hr     low  
4172                       0     support     low  
12492                      0          hr  medium

In [23]:
df.sample(frac=0.001)

satisfaction_level  last_evaluation  number_project  \
5850                 0.83             0.75               3   
1826                 0.10             0.86               6   
3670                 0.49             0.92               5   
2828                 0.52             0.51               3   
10041                0.82             0.82               5   
136                  0.10             0.84               6   
11185                0.57             0.46               2   
12189                0.44             0.51               2   
10599                0.97             0.52               4   
299                  0.74             0.84               5   
13639                0.64             0.55               4   
2660                 0.66             0.46               4   
2308                 0.62             0.53               3   
6520                 0.20             0.70               4   
12996                0.94             0.86               3   

       average_monthly_hours  time_spend_company  Work_accident  left  \
5850                     150                   3              0     0   
1826                     247                   4              0     1   
3670                     176                   3              0     0   
2828                     213                   4              0     0   
10041                    267                   2              0     0   
136                      283                   4              1     1   
11185                    100                   6              1     0   
12189                    156                   3              0     1   
10599                    207                   3              0     0   
299                      249                   5              0     1   
13639                    215                   2              0     0   
2660                     204                   4              0     0   
2308                     141                   3              0     0   
6520                     221                   5              0     0   
12996                    221                   3              1     0   

       promotion_last_5years   department  salary  
5850                       0      support     low  
1826                       0           IT  medium  
3670                       0    marketing     low  
2828                       0      support     low  
10041                      0    technical  medium  
136                        0    technical     low  
11185                      1    marketing  medium  
12189                      0    technical    high  
10599                      0  product_mng     low  
299                        0  product_mng  medium  
13639                      0        sales     low  
2660                       0  product_mng     low  
2308                       0        sales     low  
6520                       0           hr  medium  
12996                      0        sales  medium

In [24]:
import numpy as np

In [25]:
df.head()

satisfaction_level  last_evaluation  number_project  average_monthly_hours  \
0                0.38             0.53               2                    157   
1                0.80             0.86               5                    262   
2                0.11             0.88               7                    272   
3                0.72             0.87               5                    223   
4                0.37             0.52               2                    159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [26]:
sl_s = df["satisfaction_level"]

In [27]:
sl_s.isnull()

0        False
1        False
2        False
3        False
4        False
         ...  
14997    False
14998    False
14999     True
15000     True
15001    False
Name: satisfaction_level, Length: 15002, dtype: bool

In [28]:
sl_s[sl_s.isnull()]

14999   NaN
15000   NaN
Name: satisfaction_level, dtype: float64

In [30]:
df[sl_s.isnull()]

satisfaction_level  last_evaluation  number_project  \
14999                 NaN             0.52               2   
15000                 NaN        999999.00               2   

       average_monthly_hours  time_spend_company  Work_accident  left  \
14999                    158                   3              0     1   
15000                    158                   3              0     1   

       promotion_last_5years department salary  
14999                      0    support    low  
15000                      0       sale    low

In [31]:
sl_s = sl_s.dropna()

In [35]:
sl_s.isnull().any()

False

In [39]:
sl_s.mean()

0.6128393333333333

In [41]:
np.histogram(sl_s.values, bins=np.arange(0.0, 1.1, 0.1))

(array([ 195, 1214,  532,  974, 1668, 2146, 1973, 2074, 2220, 2004],
       dtype=int64),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))

In [42]:
df.head()


satisfaction_level  last_evaluation  number_project  average_monthly_hours  \
0                0.38             0.53               2                    157   
1                0.80             0.86               5                    262   
2                0.11             0.88               7                    272   
3                0.72             0.87               5                    223   
4                0.37             0.52               2                    159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [43]:
le_s = df["last_evaluation"]

In [44]:
le_s.isnull().any()

False

In [45]:
le_s.mean()

67.37373216904412

In [46]:
le_s.var()

66657550.21379456

In [47]:
le_s.std()

8164.407523745649

In [48]:
le_s.median()

0.72

In [49]:
le_s[le_s.isnull()]

Series([], Name: last_evaluation, dtype: float64)

In [50]:
le_s.max()

999999.0

In [51]:
le_s.min()

0.36

In [52]:
le_s.skew()

122.48265175204614

In [53]:
le_s.kurt()

15001.999986807796

In [54]:
le_s[le_s > 1.0]

15000    999999.0
Name: last_evaluation, dtype: float64

In [55]:
le_s > 1

0        False
1        False
2        False
3        False
4        False
         ...  
14997    False
14998    False
14999    False
15000     True
15001    False
Name: last_evaluation, Length: 15002, dtype: bool

In [56]:
le_s = le_s[le_s <= 1]

In [57]:
le_s

0        0.53
1        0.86
2        0.88
3        0.87
4        0.52
         ... 
14996    0.53
14997    0.96
14998    0.52
14999    0.52
15001    0.40
Name: last_evaluation, Length: 15001, dtype: float64

In [58]:
np.histogram(le_s.values, bins=np.arange(0.0, 1.1, 0.1))

(array([   0,    0,    0,  179, 1390, 3396, 2234, 2062, 2752, 2988],
       dtype=int64),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))

In [59]:
df.head()

satisfaction_level  last_evaluation  number_project  average_monthly_hours  \
0                0.38             0.53               2                    157   
1                0.80             0.86               5                    262   
2                0.11             0.88               7                    272   
3                0.72             0.87               5                    223   
4                0.37             0.52               2                    159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [60]:
nup = df["number_project"]


In [61]:
nup[nup.isnull()]

Series([], Name: number_project, dtype: int64)

In [62]:
nup.mean()

3.8026929742700974

In [63]:
nup.std()

1.232732779200601

In [64]:
nup.median()

4.0

In [65]:
nup.skew()

0.3377744235231047

In [66]:
nup.kurt()

-0.49580962709450604

In [67]:
nup.value_counts()

4    4365
3    4055
5    2761
2    2391
6    1174
7     256
Name: number_project, dtype: int64

In [70]:
nup.value_counts(normalize=True).sort_values()

7    0.017064
6    0.078256
2    0.159379
5    0.184042
3    0.270297
4    0.290961
Name: number_project, dtype: float64

In [71]:
df.head()

satisfaction_level  last_evaluation  number_project  average_monthly_hours  \
0                0.38             0.53               2                    157   
1                0.80             0.86               5                    262   
2                0.11             0.88               7                    272   
3                0.72             0.87               5                    223   
4                0.37             0.52               2                    159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [72]:
amh_s = df["average_monthly_hours"]

In [74]:
amh_s[amh_s.isnull()]

Series([], Name: average_monthly_hours, dtype: int64)

In [76]:
amh_s.mean()

201.0417277696307

In [77]:
amh_s.max()

310

In [78]:
amh_s.min()

96

In [79]:
amh_s.std()

49.94181527437925

In [80]:
amh_s.skew()

0.05322458779916304

In [81]:
amh_s.kurt()

-1.1350158577565719

In [89]:
amh_s = amh_s[amh_s < amh_s.quantile(0.75) + 1.5 * (amh_s.quantile(0.75) - amh_s.quantile(0.25))][amh_s > amh_s.quantile(0.25) - 1.5 * (amh_s.quantile(0.75) - amh_s.quantile(0.25))]

In [88]:
amh_s.value_counts(bins=np.arange(amh_s.min(), amh_s.max() + 10, 10))

(146.0, 156.0]     1277
(136.0, 146.0]     1159
(256.0, 266.0]     1063
(236.0, 246.0]     1006
(156.0, 166.0]      995
(246.0, 256.0]      987
(126.0, 136.0]      886
(216.0, 226.0]      873
(266.0, 276.0]      860
(166.0, 176.0]      832
(226.0, 236.0]      814
(176.0, 186.0]      813
(186.0, 196.0]      761
(196.0, 206.0]      755
(206.0, 216.0]      731
(276.0, 286.0]      319
(95.999, 106.0]     187
(286.0, 296.0]      164
(116.0, 126.0]      162
(106.0, 116.0]      162
(296.0, 306.0]      128
(306.0, 316.0]       68
Name: average_monthly_hours, dtype: int64

In [90]:
df = df.dropna(axis=0, how="any")

In [91]:
df.groupby("department").mean()

satisfaction_level  last_evaluation  number_project  \
department                                                         
IT                     0.618142         0.716830        3.816626   
RandD                  0.619822         0.712122        3.853875   
accounting             0.582151         0.717718        3.825293   
hr                     0.598809         0.708850        3.654939   
management             0.621349         0.724000        3.860317   
marketing              0.618601         0.715886        3.687646   
product_mng            0.619634         0.714756        3.807095   
sale                   0.700000         0.400000        2.000000   
sales                  0.614447         0.709717        3.776329   
support                0.618300         0.723109        3.803948   
technical              0.607897         0.721099        3.877941   

             average_monthly_hours  time_spend_company  Work_accident  \
department                                                              
IT                      202.215974            3.468623       0.133659   
RandD                   200.800508            3.367217       0.170267   
accounting              201.162973            3.522816       0.125163   
hr                      198.684709            3.355886       0.120433   
management              201.249206            4.303175       0.163492   
marketing               199.385781            3.569930       0.160839   
product_mng             199.965632            3.475610       0.146341   
sale                    158.000000            2.000000       0.000000   
sales                   200.911353            3.534058       0.141787   
support                 200.758188            3.393001       0.154778   
technical               202.497426            3.411397       0.140074   

                 left  promotion_last_5years  
department                                    
IT           0.222494               0.002445  
RandD        0.153748               0.034307  
accounting   0.265971               0.018253  
hr           0.290934               0.020298  
management   0.144444               0.109524  
marketing    0.236597               0.050117  
product_mng  0.219512               0.000000  
sale         1.000000               0.000000  
sales        0.244928               0.024155  
support      0.248991               0.008973  
technical    0.256250               0.010294